CREATE TABLE promo_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    discount_type VARCHAR(20) NOT NULL,
    discount_value DECIMAL(12,2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    valid_from DATE,
    valid_until DATE,
    minimum_subtotal DECIMAL(12,2),
    max_uses INT,
    used_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_promo_code UNIQUE (code),
    CONSTRAINT chk_promo_discount_type CHECK (discount_type IN ('PERCENTAGE', 'FIXED_AMOUNT')),
    CONSTRAINT chk_promo_discount_value CHECK (discount_value > 0),
    CONSTRAINT chk_promo_percentage CHECK (discount_type <> 'PERCENTAGE' OR discount_value <= 100),
    CONSTRAINT chk_promo_minimum_subtotal CHECK (minimum_subtotal IS NULL OR minimum_subtotal >= 0),
    CONSTRAINT chk_promo_max_uses CHECK (max_uses IS NULL OR max_uses > 0),
    CONSTRAINT chk_promo_used_count CHECK (used_count >= 0),
    CONSTRAINT chk_promo_valid_dates CHECK (
        valid_from IS NULL OR valid_until IS NULL OR valid_until >= valid_from
    )
);

ALTER TABLE reservations ADD COLUMN subtotal_price DECIMAL(12,2);
ALTER TABLE reservations ADD COLUMN discount_amount DECIMAL(12,2);
ALTER TABLE reservations ADD COLUMN promo_code VARCHAR(50);

UPDATE reservations SET subtotal_price = total_price, discount_amount = 0;

ALTER TABLE reservations ALTER COLUMN subtotal_price SET NOT NULL;
ALTER TABLE reservations ALTER COLUMN discount_amount SET NOT NULL;
ALTER TABLE reservations DROP CONSTRAINT chk_reservation_total_price;
ALTER TABLE reservations ADD CONSTRAINT chk_reservation_subtotal CHECK (subtotal_price > 0);
ALTER TABLE reservations ADD CONSTRAINT chk_reservation_discount CHECK (
    discount_amount >= 0 AND discount_amount <= subtotal_price
);
ALTER TABLE reservations ADD CONSTRAINT chk_reservation_total_price CHECK (total_price >= 0);
ALTER TABLE reservations ADD CONSTRAINT chk_reservation_price_balance CHECK (
    total_price = subtotal_price - discount_amount
);
